#!/bin/bash

echo ; echo ; echo ; 
echo "... Usage ..............................................................."
echo "./appendDataToJSONFile.sh inputJSONFileTemplate.json inputVariable dataFile"
echo ".........................................................................."
echo ;
echo "inputJSONFileTemplate.json : This file varies depending on the data structure of the 
      chart chosen to plot"
echo "inputVariable : Lookup for this variable inside inputJSONFileTemplate.json"
echo "dataFile : This is generated by AutoCMS"
echo "==============================================================="
echo "This script replaces a choice of dataVariable (second argument)" 
echo ",one at a time with data generated to a dataFile (third argument)"
echo "by AutoCMS to an inputJSON template file"
echo "==============================================================="

echo "To know the number of labels available run ./appendDataToJSONFile.sh <yourJSONFile.json>"

fileName=$1
fileExtension=${fileName#*.}

if [ "${fileExtension}" != "json" ]; then

	echo "Please check your filetype, it should be a JSON file yourFile.json"; echo; echo; 
	exit 0
fi

if [ "${fileExtension}" == "json" ]; then
	numberOfLabels=`grep -R myData $1 | wc -l` 
	echo "The number of labels that needs to be replaced in the file $1 are ${numberOfLabels}"

fi

if [ $# -ne 3 ]; then

	echo "Please check the number of arguments";
	echo; echo; echo; 
	exit 0;
fi 

# Takes the first argument from commandline inputJSONFile
echo; 
echo "Before replacing data"
cat $1
echo; echo; echo; 

# Takes the second argument from commandline, replacementVariable
# third argument from commandline dataFile and
# replaces the variable with dataFile in the new file
value=$(<$3)
echo Contents from the data file : $value

perl -pi -e "s/$2/$value/g" $1

echo "After replacement with data"; echo;
cat $1

